source = ./resources/env.conf
source = ./resources/bind.conf
source = ./resources/animations.conf
source = ./resources/autostart.conf
source = ./resources/input.conf
source = ./resources/monitors.conf
source = ./resources/windows.conf